controller_list:
  - name: fake_jaco_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
  - name: fake_jaco_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - j2n6s300_joint_finger_1
      - j2n6s300_joint_finger_tip_1
      - j2n6s300_joint_finger_2
      - j2n6s300_joint_finger_tip_2
      - j2n6s300_joint_finger_3
      - j2n6s300_joint_finger_tip_3
initial:  # Define initial robot poses per group
  - group: jaco_arm
    pose: robot_ready
  - group: jaco_hand
    pose: tool_open