controller_list:
  - name: jaco_arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j2n6s300_joint_1
      - j2n6s300_joint_2
      - j2n6s300_joint_3
      - j2n6s300_joint_4
      - j2n6s300_joint_5
  - name: jaco_hand_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - j2n6s300_joint_finger_1
      - j2n6s300_joint_finger_tip_1
      - j2n6s300_joint_finger_2
      - j2n6s300_joint_finger_tip_2
      - j2n6s300_joint_finger_3
      - j2n6s300_joint_finger_tip_3